version: '3'

# Must set:
# - HB_DATABASE_CONNECTIONSTRING
# - HB_OAUTH_CLIENTID
# - HB_OAUTH_CLIENTSECRET

volumes:
  photos:

services:
  app:
    image: docker.pkg.github.com/eliefaart/hummingbird/hummingbird-app:latest
    restart: always
    ports:
      - "29701:80"
    environment:
      API_URI: "http://server:8000"
  server:
    image: docker.pkg.github.com/eliefaart/hummingbird/hummingbird-server:latest
    restart: always
    environment:
      HB_DATABASE_CONNECTIONSTRING: "XXX"
      HB_DATABASE_NAME: "hummingbird"
      HB_STORAGE_DIRECTORYPHOTOS: "/srv/photos"
      HB_OAUTH_CLIENTID: "XXX"
      HB_OAUTH_CLIENTSECRET: "XXX"
    volumes:
      - "photos:/srv/photos"
    ports:
      - "29702:8000"