version: '3'

volumes:
  photos: null
services:
  upholi:
    image: docker.pkg.github.com/eliefaart/upholi/upholi:latest
    restart: always
    ports:
      - "29701:8000"
    environment:
      UPHOLI_DATABASE_CONNECTIONSTRING: "XXX"
      UPHOLI_STORAGE_PROVIDER: "Azure"
      UPHOLI_STORAGE_AZURESTORAGEACCOUNTNAME: "XXX"
      UPHOLI_STORAGE_AZURESTORAGEACCOUNTKEY: "XXX"
