version: '3'

# Must modify:
# - HB_DB_CONNSTRING
# May modify:
# - 'outer' ports
# - HB_DB_NAME

services:
  app:
    image: docker.pkg.github.com/eliefaart/hummingbird/hummingbird-app:docker
    restart: always
    ports:
      - "29701:80"
    environment:
      API_URI: "http://server:8000"
  server:
    image: docker.pkg.github.com/eliefaart/hummingbird/hummingbird-server:docker
    restart: always
    environment:
      HB_DB_CONNSTRING: "XXX"
      HB_DB_NAME: "hummingbird"
      HB_DIR_PHOTOS: "/srv/hummingbird/photos"
    ports:
      - "29702:8000"