version: "3"

volumes:
  photos: null
services:
  upholi:
    image: ghcr.io/eliefaart/upholi/upholi:latest
    restart: always
    ports:
      - "29701:3000"
    volumes:
      - photos:/var/upholi
    environment:
      UPHOLI_DATABASE_CONNECTIONSTRING: "XXX"
      UPHOLI_STORAGE_PROVIDER: "Disk"
      UPHOLI_STORAGE_DIRECTORYPHOTOS: "/var/upholi"
      #UPHOLI_STORAGE_AZURESTORAGEACCOUNTNAME: "XXX"
      #UPHOLI_STORAGE_AZURESTORAGEACCOUNTKEY: "XXX"
