[server]
# Address to bind to
address = "0.0.0.0:8000"
# Path of directory containing the website files.
# Can also by set using env var UPHOLI_SERVER_WWWROOT_PATH
wwwroot_path = "../app/wwwroot"

[database]
# Connection string to database
# Can also by set using env var UPHOLI_DATABASE_CONNECTIONSTRING
connection_string = ""

[storage]
# Possible values: Disk | Azure
# Can also by set using env var UPHOLI_STORAGE_PROVIDER
provider = "Disk"
# [Required if provider = "Disk"]
# Path to directory where photos will be stored
# Can also by set using env var UPHOLI_STORAGE_DIRECTORYPHOTOS
directory_photos = "/srv/upholi/photos"
# [Required if provider = "Azure"]
# Azure Storage Account name
# Can also by set using env var UPHOLI_STORAGE_AZURESTORAGEACCOUNTNAME
azure_storage_account_name = ""
# [Required if provider = "Azure"]
# Master key of Azure Storage Account
# Can also by set using env var UPHOLI_STORAGE_AZURESTORAGEACCOUNTKEY
azure_storage_account_key = ""