[server]
# Address to bind to
address = "0.0.0.0:8000"

[database]
# Connection string to database
# Can also by set using env var HB_DATABASE_CONNECTIONSTRING
connection_string = ""
# Name of database to use
# Can also by set using env var HB_DATABASE_NAME
name = "upholi"

[storage]
# Possible values: Disk | Azure
# Can also by set using env var HB_STORAGE_PROVIDER
provider = "Azure"
# [Required if provider = "Disk"]
# Path to directory where photos will be stored
# Can also by set using env var HB_STORAGE_DIRECTORYPHOTOS
directory_photos = "/srv/upholi/photos"
# [Required if provider = "Azure"]
# Azure Storage Account name
# Can also by set using env var HB_STORAGE_AZURESTORAGEACCOUNTNAME
azure_storage_account_name = "upholi"
# [Required if provider = "Azure"]
# Master key of Azure Storage Account
# Can also by set using env var HB_STORAGE_AZURESTORAGEACCOUNTKEY
azure_storage_account_key = ""