[package]
name = "upholi"
version = "0.1.0"
authors = ["Eric Liefaart <eric@e10t.nl>"]
license = ""
edition = "2018"

[dependencies]
http = "0.2.1"
serde = "1.0.106"
base64 = "0.12.0"
image = "0.23.4"
futures = "0.3.4"
actix-web = "3.3.2"
#actix-rt = "2.2.0"
actix-service = "2.0.0"
actix-multipart = "0.3.0"
actix-form-data = "0.5.0"
actix-cors = "0.5.4"
actix-http = "2.2.0"
mongodb = { version = "1.2.0", default-features = false, features = [ "sync" ] }
bson = "1.2.0"
rand = "0.7.3"
bytes = "0.5.4"
md5 = "0.7.0"
uuid = { version = "0.8.1", features = ["v4"] }
lazy_static = "1.4.0"
rexif = "0.5.0"
chrono = { version = "0.4.11", features = ["serde"] }
oauth2 = "3.0.0"
reqwest = { version = "0.11", features = ["json"] }
futures-util = "0.3.5"
config = "0.10.1"
async-trait = "0.1.36"
pbkdf2 = "0.7.2"
once_cell = "1.7.2" # required by 'azure-sdk-for-rust'
azure_core = { git = "https://github.com/Azure/azure-sdk-for-rust" }
azure_storage = { git = "https://github.com/Azure/azure-sdk-for-rust" }

#azure_storage = { git = "https://github.com/Azure/azure-sdk-for-rust/tree/master/sdk/storage" }