[package]
name = "upholi"
version = "0.1.0"
authors = ["Eric Liefaart <eric@e10t.nl>"]
license = "MIT"
edition = "2018"

[dependencies]
http = "0.2.1"
serde = "1.0.106"
base64 = "0.12.0"
image = "0.23.4"
futures = "0.3.4"
actix-web = "2.0.0"
actix-rt = "1.1.0"
actix-service = "1.0.5"
actix-multipart = "0.2.0"
actix-form-data = "0.4.0"
actix-cors = "0.2.0"
actix-http = "1.0.1"
mongodb = { version = "1.2.0", default-features = false, features = [ "sync" ] }
bson = "1.2.0"
rand = "0.7.3"
bytes = "0.5.4"
md5 = "0.7.0"
uuid = { version = "0.8.1", features = ["v4"] }
lazy_static = "1.4.0"
rexif = "0.5.0"
chrono = { version = "0.4.11", features = ["serde"] }
oauth2 = "3.0.0"
reqwest = { version = "0.10.6", features = ["json"] }
futures-util = "0.3.5"
config = "0.10.1"
async-trait = "0.1.36"
pbkdf2 = "0.7.2"
png = "0.16.8"