[package]
name = "test"
version = "0.1.0"
authors = ["Eric Liefaart <eric@e10t.nl>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# [dependencies]
# wasm-bindgen = "0.2.63"

# [dev-dependencies]
# wasm-bindgen-test = "0.3.13"
