[package]
name = "wasm"
version = "0.1.0"
authors = ["Eric Liefaart <eric@e10t.nl>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.25"
wasm-bindgen-futures = "0.4.24"
js-sys = "0.3.51"
aes-gcm-siv = "0.10.0"
uuid = { version = "0.8.1", features = ["v4", "wasm-bindgen"] }
image = { version = "0.23.12", default-features = false, features = ["gif", "jpeg", "ico", "png", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt", "dds", "farbfeld"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.11", features = ["serde"] }
rexif = "0.7.3"
reqwest = { version = "0.11.4", features = ["json"] }