name: Continuous integration - Frontend app

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/ci-app.yml'
      - 'app/*'
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: TODO
      run: |
        echo TODO