name: Continuous integration - Frontend app

on:
  push:
    paths:
      - '.github/workflows/ci-app.yml'
      - 'app/**'
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup Node.JS
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Build
      run: |
        cd ./app
        npm install
        npm run build-prd