name: Continuous integration - Server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  paths:
    - '.github/workflows/ci-server.yml'
    - 'server/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Server - Build
      run: |
        cd ./server
        cargo build --verbose
        
    - name: Server - Run tests
      run: |
        cd ./server
        cargo test --verbose