name: Docker Image

on:
  push:
    branches: [ master, docker ]
  pull_request:
    branches: [ master, docker ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up --build -d
