name: Publish - Frontend app

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/publish-app.yml'
      - 'app/**'

env:
  IMAGE_NAME: hummingbird-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Authenticate 
    - name: Log into GitHub registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    # Setup Node.JS
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    # Build
    - name: Build
      run: |
        cd ./app
        npm install
        npm run build-prd

    # Build docker
    - name: Frontend app - Build docker image
      run: |
        cd ./app
        docker build . --file Dockerfile --tag $IMAGE_NAME

    # Publish docker
    - name: Frontend app - Push docker image
      run: |
        cd ./app
        IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
        
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION

        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION