name: Server

on:
  push:
    branches: *
  pull_request:
    branches: *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd ./server && cargo build --verbose
    - name: Run tests
      run: cd ./server && cargo test --verbose
