name: wasm

on:
  push:
    paths:
      - '.github/workflows/wasm.yml'
      - 'wasm/**'
      - 'lib/**'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        cd ./wasm
        cargo build --verbose

    - name: Test
      run: |
        cd ./wasm
        cargo test --verbose

    - name: Clippy
      run: |
        cd ./wasm
        cargo clippy --all -- -D warnings

    - name: Format
      run: |
        cd ./wasm
        cargo fmt --all -- --check